spring.application.name=ntriniw-backend
spring.data.mongodb.uri=mongodb://localhost:27017/ntriniw
spring.data.mongodb.database=ntriniw
app.secret.key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
